### ISSUE TITLE
deprecated solr fields

### ISSUE THREAD

**Issue by drh-stanford** [OpenGeoMetadata/edu.princeton.arks#30]
We've deprecated several of the `solr_` fields in GeoBlacklight.

* `solr_bbox`: We use `solr_geom` instead. See https://github.com/geoblacklight/geoblacklight/issues/297
* `solr_ne_pt` and `solr_sw_pt`: These are deprecated for `solr_geom`
* `solr_wms_url`, `solr_wfs_url`, and `solr_wcs_url`: These are deprecated for `dct_references_s`.

I have the changes on my laptop but I cannot push them up to github for some reason I haven't been able to debug...

```
% git push origin deprecate-solr-bbox
Counting objects: 87837, done.
Connection to github.com closed by remote host.
fatal: The remote end hung up unexpectedly
Delta compression using up to 4 threads.
Compressing objects: 100% (44940/44940), done.
error: pack-objects died of signal 13
error: failed to push some refs to 'git@github.com:OpenGeoMetadata/edu.princeton.arks.git'
```

Thanks,
-Darren

**Comment by drh-stanford** [comment]
I was successful pushing (after a `git repack`) but I'm not 100% sure it worked correctly. See #31

**Comment by eliotjordan** [comment]
@drh-stanford Looks like the commit gutted all geoblacklight.xml files. Weird.

**Comment by drh-stanford** [comment]
Yeah, I've had zero success so far. I'll try one more time :).

**Comment by eliotjordan** [comment]
@drh-stanford I'm working on right now. I think I might be able to get it to go.

**Comment by drh-stanford** [comment]
Ok, I submitted #33 PR but it needs to be rebased. I think it'd be easier for you to regenerate a clean copy and that way it's in the generation code.

**Comment by eliotjordan** [comment]
I was able to trim down the repo by removing the preview jpegs and then issuing:
```bash
git reset $(git commit-tree HEAD^{tree} -m "create an orphan commit via commit-tree")
```
I think this needs to be done as regular maintenance, especially after making large commits. Also, keeping blobs out of the repo is helpful. We're pushing at the limits of git here. I was able to clone the repo in just over ten minutes, start to finish. Not too shabby.

**Comment by eliotjordan** [comment]
@drh-stanford See if this works on your end. If so, I can close #33.

**Comment by drh-stanford** [comment]
Ok, I submitted #33 PR but it needs a rebase and that failed.

**Comment by drh-stanford** [comment]
I think we have to prune objects from dead branches too. I'm seeing 350k objects in my git repo.

**Comment by eliotjordan** [comment]
Oh. Sorry. I didn't take a close enough look at that PR. Let me work on it a bit.

**Comment by drh-stanford** [comment]
Yeah that PR failed so I closed it. My final attempt :)
